sharedlibs: get libraries full path and ld.so path.
Parse the ldd output to get the full path of the needed shared libraries.
Use elf program header PT_INTERP type to retrived the ld.so full path.

This will make the build work on various linux distros.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -18,25 +18,35 @@ eval $(go env)
 export GOBIN=${CURDIR}/bin
 
 echo "Building sharedlibs helper..."
-go build -o ${GOBIN}/sharedlibs ${REPO_PATH}/helpers/sharedlibs
-RET=$?
-[ $RET -ne 0 ] && echo "build failed" && exit 1
-
-echo "Building bacibuilder..."
-BACIBUILDER=${GOBIN}/bacibuilder
-CGO_ENABLED=0 go build -o ${BACIBUILDER} -a -installsuffix cgo -ldflags '-extldflags "-static" -s' ${REPO_PATH}/builder
+go build -i -o ${GOBIN}/sharedlibs ${REPO_PATH}/helpers/sharedlibs
 RET=$?
 [ $RET -ne 0 ] && echo "build failed" && exit 1
 
 XZ=$(which xz)
 if [ -n $XZ ]; then
-	XZ_SHAREDLIBS=$(${GOBIN}/sharedlibs $XZ)
+	XZ_SHAREDLIBS=$(${GOBIN}/sharedlibs libs ${XZ})
+	[ $RET -ne 0 ] && echo "cannot find sharedlibs for ${XZ}" && exit 1
+	LDPATH=$(${GOBIN}/sharedlibs ldpath $XZ)
+	[ $RET -ne 0 ] && echo "cannot find ldpath for ${XZ}" && exit 1
 else
 	echo "warning: cannot find xz binary, baci will not be able to extract tar.xz files"
 fi
 
+echo "Building bacibuilder..."
+BACIBUILDER=${GOBIN}/bacibuilder
+LDFLAGS="-X github.com/sgotti/baci/builder/util.ldpath ${LDPATH}"
+
+# TODO(sgotti) not using 'go install' or 'go build -i' to avoid problems with
+# "-installsuffix" that will rebuild std libraries and can give permission
+# problems for go installation not owned by the current user (plus this will
+# fill systems dirs with build files). This means the the build should be faster
+# as, now, no object files are saved in the $GOPATH/pkg directory
+CGO_ENABLED=0 go build -o ${BACIBUILDER} -installsuffix cgo -ldflags "${LDFLAGS} --extldflags \"-static -s\" " ${REPO_PATH}/builder
+RET=$?
+[ $RET -ne 0 ] && echo "build failed" && exit 1
+
 echo "Building baci..."
-CGO_ENABLED=0 go build -o ${GOBIN}/baci ${BACI_IMAGE:+-ldflags "-X main.defaultBaciImage '${BACI_IMAGE}'"} ${REPO_PATH}/baci
+go build -i -o ${GOBIN}/baci ${BACI_IMAGE:+-ldflags "-X main.defaultBaciImage '${BACI_IMAGE}'"} ${REPO_PATH}/baci
 RET=$?
 [ $RET -ne 0 ] && echo "build failed" && exit 1
 
@@ -53,7 +63,6 @@ mkdir -p ${BACIDIR}/dest
 mkdir -p ${BACIDIR}/data
 
 mkdir -p ${BACIROOT}/usr/bin
-mkdir -p ${BACIROOT}/lib64
 
 cp ${CURDIR}/manifest ${BACIACI}
 cp ${BACIBUILDER} ${BACIROOT}/usr/bin
@@ -61,14 +70,16 @@ cp ${BACIBUILDER} ${BACIROOT}/usr/bin
 if [ -n $XZ ]; then
 	cp $XZ ${BACIROOT}/usr/bin/
 	for lib in ${XZ_SHAREDLIBS}; do
-		cp /lib64/$lib ${BACIROOT}/lib64/
+		mkdir -p ${BACIROOT}/$(dirname ${lib})
+		cp $lib ${BACIROOT}/$lib
 	done
-	cp /lib64/ld-linux-x86-64.so.2 ${BACIROOT}/lib64/
+	mkdir -p ${BACIROOT}/$(dirname ${LDPATH})
+	cp $LDPATH ${BACIROOT}/$LDPATH
 fi
 
 echo "Building actool..."
 ACTOOL=${GOBIN}/actool
-go build -o ${ACTOOL} ${REPO_PATH}/Godeps/_workspace/src/github.com/appc/spec/actool
+go build -i -o ${ACTOOL} ${REPO_PATH}/Godeps/_workspace/src/github.com/appc/spec/actool
 
 echo "Creating the baci's ACI..."
 ${ACTOOL} build --overwrite ${CURDIR}/aci ${GOBIN}/baci.aci
